"""
Case routes.

FastAPI endpoints for creating and viewing investigation cases.

IMPORTANT ARCHITECTURE NOTE: there is no database in this project.
Cases are held only in a module-level Python dict for the lifetime of
the running server process. Restarting the server clears every case -
see the module-level docstring below the imports for the full
explanation and its consequences.

This file defines routes ONLY. It reuses:
    - app.models.case.Case          (the internal data model)
    - app.schemas.case.CaseCreate   (request shape for POST /cases)
    - app.schemas.case.CaseResponse (response shape for all endpoints)

No evidence upload, timeline, analysis, or report functionality is
implemented here - only case CRUD-in-memory (create, list, get-by-id).
"""

from typing import Dict, List

from fastapi import APIRouter, HTTPException, status

from app.models.case import Case
from app.schemas.case import CaseCreate, CaseResponse

router = APIRouter(prefix="/cases", tags=["cases"])

# In-memory case store: case.id -> Case.
#
# This is intentionally just a plain dict, not a database, not even
# SQLite. It exists only in this process's memory for as long as the
# server keeps running. See `intake_evidence_package`-style services
# for how a database WOULD eventually be introduced without touching
# this file - but for now, this dict IS the entire persistence layer
# for cases.
_cases: Dict[str, Case] = {}


@router.post("", response_model=CaseResponse, status_code=status.HTTP_201_CREATED)
def create_case(payload: CaseCreate) -> CaseResponse:
    """
    Create a new investigation case.

    `id` and `created_at` are generated by the Case model itself
    (see app.models.case.Case's field defaults) - the client only
    supplies `name` and `description` via CaseCreate.
    """
    case = Case(name=payload.name, description=payload.description)
    _cases[case.id] = case
    return CaseResponse(**case.model_dump())


@router.get("", response_model=List[CaseResponse])
def list_cases() -> List[CaseResponse]:
    """
    List every case currently held in memory.

    Order reflects insertion order (Python dicts preserve insertion
    order), i.e. the order cases were created in during this server's
    current run.
    """
    return [CaseResponse(**case.model_dump()) for case in _cases.values()]


@router.get("/{case_id}", response_model=CaseResponse)
def get_case(case_id: str) -> CaseResponse:
    """
    Retrieve a single case by id.

    Raises a 404 if no case with that id exists in memory - either it
    was never created, the id is wrong, or the server has restarted
    since it was created (see the in-memory storage note above).
    """
    case = _cases.get(case_id)
    if case is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=f"Case '{case_id}' not found")
    return CaseResponse(**case.model_dump())
