"""
Case routes.

FastAPI endpoints for creating and viewing investigation cases.

ARCHITECTURE NOTE: there is no database in this project. Cases live in
the centralized in-memory store in app/state.py for the lifetime of the
running server process - restarting the server clears every case. This
file deliberately does NOT keep its own dict of cases; app_state is the
single source of truth shared with every other route and service.

This file defines routes ONLY. It reuses:
    - app.state.app_state               (the in-memory store)
    - app.schemas.case.CaseCreate       (request shape for POST /cases)
    - app.schemas.case.CaseResponse     (response shape)

No evidence upload, timeline, analysis, or report logic lives here.
"""

from typing import List

from fastapi import APIRouter, HTTPException, status

from app.models.case import Case
from app.schemas.case import CaseCreate, CaseResponse
from app.state import app_state

router = APIRouter(prefix="/cases", tags=["cases"])


def get_case_or_404(case_id: str) -> Case:
    """
    Look up a case, raising a 404 HTTPException if it doesn't exist.

    Shared helper: every case-scoped route (evidence, timeline,
    locations, communications, analysis, report) calls this so the
    lookup and the 404 message are defined in exactly one place.
    """
    case = app_state.get_case(case_id)
    if case is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Case '{case_id}' not found",
        )
    return case


@router.post("", response_model=CaseResponse, status_code=status.HTTP_201_CREATED)
def create_case(payload: CaseCreate) -> CaseResponse:
    """
    Create a new investigation case.

    `id` and `created_at` are generated by the Case model's own field
    defaults - the client only supplies `name` and `description`.
    """
    case = app_state.create_case(name=payload.name, description=payload.description)
    return CaseResponse(**case.model_dump())


@router.get("", response_model=List[CaseResponse])
def list_cases() -> List[CaseResponse]:
    """
    List every case currently held in memory, in creation order.
    """
    return [CaseResponse(**case.model_dump()) for case in app_state.list_cases()]


@router.get("/{case_id}", response_model=CaseResponse)
def get_case(case_id: str) -> CaseResponse:
    """
    Retrieve a single case by id.

    Returns 404 if no case with that id exists - either it was never
    created, the id is wrong, or the server has restarted since it was
    created (see the in-memory storage note above).
    """
    case = get_case_or_404(case_id)
    return CaseResponse(**case.model_dump())
