"""
Full end-to-end integration test for the Mobile Device Forensic
Analysis System backend.

This test does NOT assume a server is already running. It starts its own
fresh Uvicorn subprocess on a free localhost port, waits for /health to
respond, drives the real HTTP API, and shuts the process down again -
even if a test fails.

Nothing is mocked. Every assertion travels the whole pipeline:

    HTTP -> FastAPI route -> processing service -> ZIP extraction ->
    JSON loading -> existing parsers -> normalization -> application
    state -> timeline / correlation / report -> HTTP response

The evidence ZIP is generated by this file into a temporary directory,
so no sample archive in the repository is read or modified. The server
subprocess also gets its own UPLOAD_DIR and TEMP_DIR under that same
temporary directory, so running this test never writes into
backend/uploads or backend/temp.

Run it either way:

    pytest tests/test_full_integration.py -v
    python tests/test_full_integration.py

Environment overrides:
    TEST_HOST            (default 127.0.0.1)
    TEST_PORT            (default: an automatically chosen free port)
    TEST_STARTUP_TIMEOUT (default 45, seconds to wait for /health)
"""

import atexit
import json
import os
import shutil
import socket
import subprocess
import sys
import tempfile
import time
import zipfile
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, Optional

import requests

# backend/ - the directory Uvicorn must run from for `app.main:app` to
# import, and the parent of this tests/ package.
BACKEND_DIR = Path(__file__).resolve().parent.parent

STARTUP_TIMEOUT_SECONDS = float(os.getenv("TEST_STARTUP_TIMEOUT", "45"))
HEALTH_POLL_INTERVAL_SECONDS = 0.15
REQUEST_TIMEOUT_SECONDS = 30
SHUTDOWN_GRACE_SECONDS = 10

# Deterministic synthetic timestamps. Same instants every run.
_DAY = "2026-03-01"
TS_APP = f"{_DAY}T09:00:00+00:00"
TS_CALL = f"{_DAY}T09:05:00+00:00"
TS_MESSAGE = f"{_DAY}T09:07:00+00:00"
TS_LOCATION = f"{_DAY}T09:08:00+00:00"
TS_SYSTEM = f"{_DAY}T09:10:00+00:00"

# Shared synthetic identifier appearing on both a call and a message, so
# the existing shared_identifier rule has something deterministic to find.
SHARED_CONTACT = "+1-555-0100"

SYNTHETIC_LATITUDE = 12.6271
SYNTHETIC_LONGITUDE = 80.1927


# =====================================================================
# Server lifecycle
# =====================================================================


class BackendServer:
    """A Uvicorn subprocess running app.main:app, started for this test run."""

    def __init__(self) -> None:
        self.host = os.getenv("TEST_HOST", "127.0.0.1")
        self.port = int(os.getenv("TEST_PORT", "0")) or _find_free_port()
        self.base_url = f"http://{self.host}:{self.port}"
        self.process: Optional[subprocess.Popen] = None
        self._workspace: Optional[str] = None
        self._log_file = None
        self._log_path: Optional[Path] = None

    def start(self) -> None:
        """Launch the subprocess and block until /health answers."""
        # A plain mkdtemp, not TemporaryDirectory: the latter registers a
        # finalizer that calls rmtree at interpreter exit, and on Windows
        # that raises PermissionError if any handle on server.log is still
        # open - burying the real startup error under a second traceback.
        # Cleanup here is explicit, ordered, and never raises.
        self._workspace = tempfile.mkdtemp(prefix="forensic_test_")
        workspace = Path(self._workspace)
        (workspace / "uploads").mkdir()
        (workspace / "temp").mkdir()

        env = os.environ.copy()
        env["UPLOAD_DIR"] = str(workspace / "uploads")
        env["TEMP_DIR"] = str(workspace / "temp")
        env["PYTHONUNBUFFERED"] = "1"

        self._log_path = workspace / "server.log"
        # Opened write-only; read_log() opens its own separate handle, so
        # reading the log never interferes with the subprocess writing it.
        self._log_file = open(self._log_path, "w", encoding="utf-8")

        self.process = subprocess.Popen(
            [
                sys.executable,
                "-m",
                "uvicorn",
                "app.main:app",
                "--host",
                self.host,
                "--port",
                str(self.port),
                "--log-level",
                "warning",
            ],
            cwd=str(BACKEND_DIR),
            env=env,
            stdout=self._log_file,
            stderr=subprocess.STDOUT,
        )

        try:
            self._wait_for_health()
        except BaseException:
            # Startup failed (or was interrupted). Release the subprocess
            # and its log handle before propagating, so the caller sees the
            # real error rather than a cleanup error on top of it.
            self.stop()
            raise

    def _wait_for_health(self) -> None:
        """Poll /health until it answers, the process dies, or we time out."""
        deadline = time.monotonic() + STARTUP_TIMEOUT_SECONDS

        while time.monotonic() < deadline:
            if self.process is not None and self.process.poll() is not None:
                output = self.read_log()
                raise RuntimeError(
                    "Backend process exited during startup "
                    f"(exit code {self.process.returncode}).\n"
                    f"{_startup_hint(output)}\n"
                    f"--- server output ---\n{output}"
                )
            try:
                response = requests.get(f"{self.base_url}/health", timeout=2)
                if response.status_code == 200:
                    return
            except requests.RequestException:
                pass
            time.sleep(HEALTH_POLL_INTERVAL_SECONDS)

        raise RuntimeError(
            f"Backend did not become healthy within {STARTUP_TIMEOUT_SECONDS}s at "
            f"{self.base_url}/health.\n\n--- server output ---\n{self.read_log()}"
        )

    def read_log(self) -> str:
        """Whatever the subprocess has written so far, for failure reporting."""
        if self._log_path is None or not self._log_path.exists():
            return "(no server output captured)"
        try:
            return self._log_path.read_text(encoding="utf-8", errors="replace").strip() or "(empty)"
        except OSError as exc:
            return f"(could not read server log: {exc})"

    def stop(self) -> None:
        """
        Terminate the subprocess and clean up its workspace.

        Safe to call more than once, and never raises: a failure to tidy
        up must not mask whatever actually went wrong in the tests.
        Order matters on Windows - the child process has to be gone and
        the log handle closed before the directory can be removed.
        """
        if self.process is not None:
            if self.process.poll() is None:
                self.process.terminate()
                try:
                    self.process.wait(timeout=SHUTDOWN_GRACE_SECONDS)
                except subprocess.TimeoutExpired:
                    self.process.kill()
                    try:
                        self.process.wait(timeout=SHUTDOWN_GRACE_SECONDS)
                    except subprocess.TimeoutExpired:
                        pass
            self.process = None

        if self._log_file is not None:
            try:
                self._log_file.close()
            except OSError:
                pass
            self._log_file = None

        if self._workspace is not None:
            shutil.rmtree(self._workspace, ignore_errors=True)
            self._workspace = None


def _startup_hint(output: str) -> str:
    """
    Turn a known-shape startup failure into one actionable line.

    The import error below is by far the most common way this fails: an
    editor's "optimize imports" action rewrites `from app.api.routes.x`
    into `from api.routes.x`, which only resolves if backend/app is on
    sys.path - it isn't, because Uvicorn runs from backend/.
    """
    if "No module named 'api'" in output or "No module named 'core'" in output:
        return (
            "\nHINT: an import inside backend/app/ has lost its leading `app.`.\n"
            "      Every internal import must read `from app.<package>...`,\n"
            "      e.g. `from app.api.routes.cases import router`.\n"
            "      An IDE \"optimize imports\" action commonly strips it.\n"
        )
    if "No module named 'app'" in output:
        return (
            "\nHINT: Uvicorn could not find the `app` package. It must run with\n"
            "      backend/ as its working directory.\n"
        )
    if "No module named" in output:
        return (
            "\nHINT: a dependency is missing. Run:\n"
            "      pip install -r requirements.txt\n"
        )
    return ""


def _check_backend_imports() -> None:
    """
    Import the FastAPI app in a throwaway subprocess before starting the
    real server, so a broken import is reported as one clear message
    instead of a Uvicorn stack trace.
    """
    result = subprocess.run(
        [sys.executable, "-c", "import app.main"],
        cwd=str(BACKEND_DIR),
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        output = (result.stderr or result.stdout).strip()
        raise RuntimeError(
            "backend/app/main.py could not be imported, so the server would "
            f"never start.\n{_startup_hint(output)}\n--- import error ---\n{output}"
        )


def _find_free_port() -> int:
    """Ask the OS for an unused localhost port."""
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.bind(("127.0.0.1", 0))
        return sock.getsockname()[1]


# One server per test session, started on first use and always stopped
# at process exit - so cleanup happens whether tests pass, fail, or
# error out. This works identically under pytest and the standalone
# runner at the bottom of this file, without needing pytest fixtures.
_server: Optional[BackendServer] = None


def base_url() -> str:
    """Start the backend if it isn't running yet, and return its base URL."""
    global _server
    if _server is None:
        _check_backend_imports()
        server = BackendServer()
        server.start()
        _server = server
        atexit.register(stop_server)
    return _server.base_url


def stop_server() -> None:
    global _server
    if _server is not None:
        _server.stop()
        _server = None


# =====================================================================
# Synthetic evidence
# =====================================================================


def build_synthetic_evidence_zip(target_dir: Path) -> Path:
    """
    Write a small, clearly synthetic evidence ZIP into `target_dir`.

    The JSON shapes here were taken from the existing parsers in
    app/parsers/ - field names and value types match what those parsers
    actually accept. The archive also contains one unsupported file, so
    the extraction service's skip behaviour is exercised too.
    """
    archive_path = target_dir / "synthetic_evidence.zip"

    device = {
        "device_id": "SYNTHETIC-DEVICE-0001",
        "model": "Simulated Handset X",
        "os_version": "SimOS 1.0",
        "owner_reference": "SYNTHETIC-SUBJECT-A",
    }
    app_activity = [
        {"timestamp": TS_APP, "app": "SimChat", "action": "OPEN"},
        {"timestamp": TS_SYSTEM, "app": "SimChat", "action": "CLOSE"},
    ]
    calls = [
        {
            "timestamp": TS_CALL,
            "contact": SHARED_CONTACT,
            "direction": "incoming",
            "duration_seconds": 95,
        }
    ]
    messages = [
        {
            "timestamp": TS_MESSAGE,
            "contact": SHARED_CONTACT,
            "direction": "outgoing",
            "content": "Synthetic test message content.",
        }
    ]
    locations = [
        {
            "timestamp": TS_LOCATION,
            "latitude": SYNTHETIC_LATITUDE,
            "longitude": SYNTHETIC_LONGITUDE,
            "label": "Synthetic Point A",
            "accuracy": 12,
            "provider": "simulated_gps",
        }
    ]
    system_logs = [
        {
            "timestamp": TS_SYSTEM,
            "level": "INFO",
            "event": "boot_completed",
            "message": "Synthetic device finished booting.",
        }
    ]

    with zipfile.ZipFile(archive_path, "w") as archive:
        archive.writestr("device.json", json.dumps(device))
        archive.writestr("app_activity.json", json.dumps(app_activity))
        archive.writestr("calls.json", json.dumps(calls))
        archive.writestr("messages.json", json.dumps(messages))
        archive.writestr("locations.json", json.dumps(locations))
        archive.writestr("system_logs.json", json.dumps(system_logs))
        archive.writestr("notes.txt", "Synthetic, unsupported file. Should be skipped.")

    return archive_path


def build_malformed_evidence_zip(target_dir: Path) -> Path:
    """
    An archive that is a valid ZIP but whose evidence files are broken
    in three different ways - used to confirm the backend reports the
    problems instead of failing the whole request.
    """
    archive_path = target_dir / "malformed_evidence.zip"

    with zipfile.ZipFile(archive_path, "w") as archive:
        # Not valid JSON at all.
        archive.writestr("messages.json", "{ this is not valid json ")
        # Valid JSON, wrong structure for the parser.
        archive.writestr("calls.json", json.dumps({"unexpected": "shape"}))
        # Valid JSON and structure, but an out-of-range coordinate that
        # the location parser must reject.
        archive.writestr(
            "locations.json",
            json.dumps([{"timestamp": TS_LOCATION, "latitude": 999.0, "longitude": 0.0}]),
        )

    return archive_path


# =====================================================================
# Helpers
# =====================================================================

# Shared across the ordered test functions below.
_ctx: Dict[str, Any] = {}


def _url(path: str) -> str:
    return f"{base_url()}{path}"


def _create_case(name: str, description: str) -> str:
    response = requests.post(
        _url("/cases"),
        json={"name": name, "description": description},
        timeout=REQUEST_TIMEOUT_SECONDS,
    )
    assert response.status_code == 201, response.text
    return response.json()["id"]


def _upload(case_id: str, archive_path: Path) -> requests.Response:
    with open(archive_path, "rb") as handle:
        return requests.post(
            _url(f"/cases/{case_id}/evidence"),
            files={"file": (archive_path.name, handle, "application/zip")},
            timeout=REQUEST_TIMEOUT_SECONDS,
        )


def _assert_iso_timestamp(value: str) -> datetime:
    parsed = datetime.fromisoformat(str(value).replace("Z", "+00:00"))
    assert parsed.year == 2026, f"Unexpected timestamp: {value}"
    return parsed


# =====================================================================
# Tests - run in definition order
# =====================================================================


def test_01_health() -> None:
    response = requests.get(_url("/health"), timeout=REQUEST_TIMEOUT_SECONDS)
    assert response.status_code == 200, response.text
    assert response.json() == {"status": "ok"}


def test_02_docs_and_openapi_are_available() -> None:
    docs = requests.get(_url("/docs"), timeout=REQUEST_TIMEOUT_SECONDS)
    assert docs.status_code == 200, docs.text

    openapi = requests.get(_url("/openapi.json"), timeout=REQUEST_TIMEOUT_SECONDS)
    assert openapi.status_code == 200, openapi.text

    paths = openapi.json()["paths"]
    expected = [
        ("/health", "get"),
        ("/cases", "post"),
        ("/cases", "get"),
        ("/cases/{case_id}", "get"),
        ("/cases/{case_id}/evidence", "post"),
        ("/cases/{case_id}/evidence", "get"),
        ("/cases/{case_id}/timeline", "get"),
        ("/cases/{case_id}/locations", "get"),
        ("/cases/{case_id}/communications", "get"),
        ("/cases/{case_id}/analysis", "get"),
        ("/cases/{case_id}/report", "get"),
    ]
    for path, method in expected:
        assert path in paths, f"{path} missing from OpenAPI schema"
        assert method in paths[path], f"{method.upper()} {path} missing from OpenAPI schema"


def test_03_create_case() -> None:
    response = requests.post(
        _url("/cases"),
        json={
            "name": "Synthetic Integration Case",
            "description": "Simulated device analysis created by test_full_integration.py",
        },
        timeout=REQUEST_TIMEOUT_SECONDS,
    )
    assert response.status_code == 201, response.text

    case = response.json()
    for key in ("id", "name", "description", "created_at"):
        assert key in case, f"Missing '{key}' in created case: {case}"
    assert case["id"]
    assert case["name"] == "Synthetic Integration Case"
    assert case["description"].startswith("Simulated device analysis")
    datetime.fromisoformat(case["created_at"].replace("Z", "+00:00"))

    _ctx["case_id"] = case["id"]


def test_04_list_cases_contains_created_case() -> None:
    response = requests.get(_url("/cases"), timeout=REQUEST_TIMEOUT_SECONDS)
    assert response.status_code == 200, response.text

    cases = response.json()
    assert isinstance(cases, list)
    assert _ctx["case_id"] in [case["id"] for case in cases]


def test_05_get_single_case() -> None:
    response = requests.get(_url(f"/cases/{_ctx['case_id']}"), timeout=REQUEST_TIMEOUT_SECONDS)
    assert response.status_code == 200, response.text
    assert response.json()["id"] == _ctx["case_id"]


def test_06_get_unknown_case_returns_404() -> None:
    response = requests.get(_url("/cases/does-not-exist"), timeout=REQUEST_TIMEOUT_SECONDS)
    assert response.status_code == 404, response.text
    assert "detail" in response.json()


def test_07_upload_synthetic_evidence() -> None:
    with tempfile.TemporaryDirectory(prefix="forensic_evidence_") as tmp_dir:
        archive = build_synthetic_evidence_zip(Path(tmp_dir))
        response = _upload(_ctx["case_id"], archive)

    assert response.status_code == 201, response.text
    payload = response.json()

    assert payload["success"] is True
    assert payload["case_id"] == _ctx["case_id"]
    assert payload["evidence_id"]
    assert payload["original_filename"] == "synthetic_evidence.zip"
    assert payload["processing_status"] == "processed", payload

    # Integrity: a 64-character lowercase hex SHA-256 digest.
    digest = payload["sha256"]
    assert isinstance(digest, str) and len(digest) == 64, digest
    assert all(char in "0123456789abcdef" for char in digest), digest

    extracted = payload["extracted_files"]
    for expected_file in (
        "device.json",
        "app_activity.json",
        "calls.json",
        "messages.json",
        "locations.json",
        "system_logs.json",
    ):
        assert expected_file in extracted, f"{expected_file} not extracted: {extracted}"

    # The unsupported file must have been skipped, not extracted.
    assert "notes.txt" not in extracted
    assert any("notes.txt" in entry.get("entry", "") for entry in payload["skipped_files"]), payload[
        "skipped_files"
    ]

    # 2 app + 1 call + 1 message + 1 location + 1 system = 6 events.
    assert payload["processed_event_count"] == 6, payload
    assert payload["normalization_error_count"] == 0, payload
    assert payload["device_info"]["device_id"] == "SYNTHETIC-DEVICE-0001"

    # No server filesystem paths leak into the response.
    assert "saved_path" not in payload
    assert "file_path" not in json.dumps(payload["evidence_items"])

    _ctx["evidence_id"] = payload["evidence_id"]


def test_07b_list_registered_evidence() -> None:
    response = requests.get(
        _url(f"/cases/{_ctx['case_id']}/evidence"), timeout=REQUEST_TIMEOUT_SECONDS
    )
    assert response.status_code == 200, response.text

    payload = response.json()
    assert payload["case_id"] == _ctx["case_id"]
    assert payload["total_files"] == 6, payload
    assert payload["total_events"] == 6, payload
    assert payload["normalization_error_count"] == 0

    filenames = {item["filename"] for item in payload["files"]}
    assert "calls.json" in filenames and "device.json" in filenames, filenames
    assert all("file_path" not in item for item in payload["files"])

    assert len(payload["packages"]) == 1, payload["packages"]
    package = payload["packages"][0]
    assert package["original_filename"] == "synthetic_evidence.zip"
    assert len(package["sha256"]) == 64
    assert payload["device_info"]["device_id"] == "SYNTHETIC-DEVICE-0001"


def test_08_timeline_contains_normalized_events() -> None:
    response = requests.get(
        _url(f"/cases/{_ctx['case_id']}/timeline"), timeout=REQUEST_TIMEOUT_SECONDS
    )
    assert response.status_code == 200, response.text

    timeline = response.json()
    assert isinstance(timeline, list)
    assert len(timeline) == 6, timeline

    categories = {event["category"] for event in timeline}
    for expected in ("app", "call", "message", "location", "system"):
        assert expected in categories, f"Missing '{expected}' events: {categories}"

    timestamps = []
    for event in timeline:
        for key in ("id", "case_id", "timestamp", "category", "event_type", "source", "description"):
            assert key in event, f"Missing '{key}' in event: {event}"
        assert event["case_id"] == _ctx["case_id"]
        timestamps.append(_assert_iso_timestamp(event["timestamp"]))

    assert timestamps == sorted(timestamps), "Timeline is not in chronological order"


def test_09_timeline_filters() -> None:
    response = requests.get(
        _url(f"/cases/{_ctx['case_id']}/timeline"),
        params={"category": "call"},
        timeout=REQUEST_TIMEOUT_SECONDS,
    )
    assert response.status_code == 200, response.text
    calls = response.json()
    assert len(calls) == 1
    assert calls[0]["category"] == "call"

    response = requests.get(
        _url(f"/cases/{_ctx['case_id']}/timeline"),
        params={"start_time": TS_MESSAGE},
        timeout=REQUEST_TIMEOUT_SECONDS,
    )
    assert response.status_code == 200, response.text
    # message 09:07, location 09:08, system 09:10, app close 09:10 -> 4
    assert len(response.json()) == 4, response.json()


def test_10_locations() -> None:
    response = requests.get(
        _url(f"/cases/{_ctx['case_id']}/locations"), timeout=REQUEST_TIMEOUT_SECONDS
    )
    assert response.status_code == 200, response.text

    locations = response.json()
    assert isinstance(locations, list)
    assert len(locations) == 1, locations

    record = locations[0]
    for key in ("id", "timestamp", "latitude", "longitude", "source", "metadata"):
        assert key in record, f"Missing '{key}' in location record: {record}"

    assert record["latitude"] == SYNTHETIC_LATITUDE
    assert record["longitude"] == SYNTHETIC_LONGITUDE
    assert -90.0 <= record["latitude"] <= 90.0
    assert -180.0 <= record["longitude"] <= 180.0
    assert record["metadata"]["label"] == "Synthetic Point A"
    _assert_iso_timestamp(record["timestamp"])


def test_11_communications() -> None:
    response = requests.get(
        _url(f"/cases/{_ctx['case_id']}/communications"), timeout=REQUEST_TIMEOUT_SECONDS
    )
    assert response.status_code == 200, response.text

    payload = response.json()
    assert payload["case_id"] == _ctx["case_id"]
    assert payload["total_calls"] == 1, payload
    assert payload["total_messages"] == 1, payload
    assert payload["total"] == 2, payload

    by_category = {record["category"]: record for record in payload["records"]}
    assert "call" in by_category and "message" in by_category, by_category

    call = by_category["call"]
    assert call["metadata"]["caller"] == SHARED_CONTACT
    assert call["metadata"]["direction"] == "incoming"
    assert call["metadata"]["duration"] == 95.0

    message = by_category["message"]
    assert message["metadata"]["receiver"] == SHARED_CONTACT
    assert message["metadata"]["direction"] == "outgoing"
    assert message["metadata"]["content"] == "Synthetic test message content."


def test_12_analysis() -> None:
    response = requests.get(
        _url(f"/cases/{_ctx['case_id']}/analysis"), timeout=REQUEST_TIMEOUT_SECONDS
    )
    assert response.status_code == 200, response.text

    payload = response.json()
    assert payload["case_id"] == _ctx["case_id"]
    assert payload["total_events"] == 6, payload
    assert isinstance(payload["correlations"], list)
    assert payload["total_correlations"] == len(payload["correlations"])
    assert payload["total_correlations"] > 0, "Synthetic data should produce correlations"

    rules = {correlation["rule"] for correlation in payload["correlations"]}
    # The synthetic data is designed so all three deterministic rules fire:
    # every event is within 15 minutes of the others, a call and a message
    # share one contact identifier, and a location sits beside other activity.
    for expected_rule in ("time_window", "shared_identifier", "location_proximity"):
        assert expected_rule in rules, f"Rule '{expected_rule}' did not appear: {rules}"

    for correlation in payload["correlations"]:
        for key in ("correlation_id", "related_event_ids", "reason", "rule", "context"):
            assert key in correlation, f"Missing '{key}' in correlation: {correlation}"
        assert len(correlation["related_event_ids"]) >= 2

    shared = [c for c in payload["correlations"] if c["rule"] == "shared_identifier"]
    assert any(c["context"].get("identifier") == SHARED_CONTACT for c in shared), shared

    # Forensic wording: no claims of guilt or criminality anywhere.
    text = json.dumps(payload).lower()
    for forbidden in ("guilty", "criminal", "proves", "committed the crime"):
        assert forbidden not in text, f"Analysis contains unsupported wording: {forbidden}"


def test_13_report() -> None:
    response = requests.get(
        _url(f"/cases/{_ctx['case_id']}/report"), timeout=REQUEST_TIMEOUT_SECONDS
    )
    assert response.status_code == 200, response.text

    report = response.json()
    for section in (
        "disclaimer",
        "case_information",
        "observed_evidence",
        "calculated_analysis",
        "potentially_related_events",
        "report_integrity",
    ):
        assert section in report, f"Missing report section '{section}'"

    assert report["case_information"]["id"] == _ctx["case_id"]
    assert report["observed_evidence"]["total_items"] == 6, report["observed_evidence"]

    analysis = report["calculated_analysis"]
    assert analysis["timeline_summary"]["event_count"] == 6
    assert analysis["location_summary"]["location_event_count"] == 1
    assert analysis["communication_summary"]["total_calls"] == 1
    assert analysis["communication_summary"]["total_messages"] == 1
    assert SHARED_CONTACT in analysis["communication_summary"]["distinct_contacts_observed"]

    assert report["potentially_related_events"]["count"] > 0
    assert report["report_integrity"]["events_included"] == 6
    assert report["report_integrity"]["records_that_failed_normalization"] == 0


def test_14_case_scoped_endpoints_404_on_unknown_case() -> None:
    for path in ("evidence", "timeline", "locations", "communications", "analysis", "report"):
        response = requests.get(
            _url(f"/cases/unknown-case-id/{path}"), timeout=REQUEST_TIMEOUT_SECONDS
        )
        assert response.status_code == 404, f"/{path} returned {response.status_code}"


def test_15_upload_to_unknown_case_returns_404() -> None:
    with tempfile.TemporaryDirectory(prefix="forensic_evidence_") as tmp_dir:
        archive = build_synthetic_evidence_zip(Path(tmp_dir))
        response = _upload("unknown-case-id", archive)
    assert response.status_code == 404, response.text


def test_16_non_zip_upload_is_rejected() -> None:
    response = requests.post(
        _url(f"/cases/{_ctx['case_id']}/evidence"),
        files={"file": ("evidence.txt", b"definitely not a zip", "text/plain")},
        timeout=REQUEST_TIMEOUT_SECONDS,
    )
    assert response.status_code == 400, response.text
    assert "detail" in response.json()


def test_17_zip_extension_but_not_a_zip_is_rejected() -> None:
    response = requests.post(
        _url(f"/cases/{_ctx['case_id']}/evidence"),
        files={"file": ("evidence.zip", b"still not a real zip archive", "application/zip")},
        timeout=REQUEST_TIMEOUT_SECONDS,
    )
    assert response.status_code == 400, response.text


def test_18_missing_file_field_returns_422() -> None:
    response = requests.post(
        _url(f"/cases/{_ctx['case_id']}/evidence"), timeout=REQUEST_TIMEOUT_SECONDS
    )
    assert response.status_code == 422, response.text


def test_19_malformed_case_payload_returns_422() -> None:
    response = requests.post(
        _url("/cases"), json={"name": ""}, timeout=REQUEST_TIMEOUT_SECONDS
    )
    assert response.status_code == 422, response.text


def test_20_malformed_evidence_is_reported_not_fatal() -> None:
    case_id = _create_case("Malformed Evidence Case", "Synthetic malformed evidence handling")

    with tempfile.TemporaryDirectory(prefix="forensic_evidence_") as tmp_dir:
        archive = build_malformed_evidence_zip(Path(tmp_dir))
        response = _upload(case_id, archive)

    assert response.status_code == 201, response.text
    payload = response.json()

    assert payload["success"] is True
    assert payload["processed_event_count"] == 0, payload
    assert payload["normalization_error_count"] >= 3, payload
    assert payload["processing_status"] == "processed_with_warnings", payload
    assert payload["warnings"], "Expected warnings about the malformed files"

    # The server is still healthy and the case still serves empty results.
    assert requests.get(_url("/health"), timeout=REQUEST_TIMEOUT_SECONDS).status_code == 200
    assert requests.get(
        _url(f"/cases/{case_id}/timeline"), timeout=REQUEST_TIMEOUT_SECONDS
    ).json() == []
    assert requests.get(
        _url(f"/cases/{case_id}/locations"), timeout=REQUEST_TIMEOUT_SECONDS
    ).json() == []

    report = requests.get(
        _url(f"/cases/{case_id}/report"), timeout=REQUEST_TIMEOUT_SECONDS
    ).json()
    assert report["report_integrity"]["records_that_failed_normalization"] >= 3


def test_21_empty_case_serves_empty_collections() -> None:
    case_id = _create_case("Empty Case", "Synthetic case with no evidence uploaded")

    assert requests.get(_url(f"/cases/{case_id}/timeline"), timeout=REQUEST_TIMEOUT_SECONDS).json() == []
    assert requests.get(_url(f"/cases/{case_id}/locations"), timeout=REQUEST_TIMEOUT_SECONDS).json() == []

    evidence = requests.get(
        _url(f"/cases/{case_id}/evidence"), timeout=REQUEST_TIMEOUT_SECONDS
    ).json()
    assert evidence["total_files"] == 0 and evidence["packages"] == []

    communications = requests.get(
        _url(f"/cases/{case_id}/communications"), timeout=REQUEST_TIMEOUT_SECONDS
    ).json()
    assert communications["total"] == 0

    analysis = requests.get(
        _url(f"/cases/{case_id}/analysis"), timeout=REQUEST_TIMEOUT_SECONDS
    ).json()
    assert analysis["total_events"] == 0
    assert analysis["correlations"] == []


# =====================================================================
# Standalone runner (no pytest required)
# =====================================================================


def _collect_tests():
    return [
        (name, obj)
        for name, obj in sorted(globals().items())
        if name.startswith("test_") and callable(obj)
    ]


def main() -> int:
    failures = []
    tests = _collect_tests()

    print(f"Running {len(tests)} integration tests against a fresh backend process.\n")

    try:
        url = base_url()
        print(f"Backend ready at {url}\n")

        for name, test in tests:
            try:
                test()
            except AssertionError as exc:
                print(f"[FAIL] {name}: {exc}")
                failures.append(name)
            except Exception as exc:  # noqa: BLE001 - report, don't abort the run
                print(f"[ERROR] {name}: {type(exc).__name__}: {exc}")
                failures.append(name)
            else:
                print(f"[PASS] {name}")
    except Exception as exc:  # noqa: BLE001 - startup failure
        print(f"\n[ERROR] Could not run tests: {exc}")
        return 1
    finally:
        stop_server()

    print()
    if failures:
        print(f"{len(failures)} of {len(tests)} tests FAILED: {', '.join(failures)}")
        return 1

    print(f"All {len(tests)} tests PASSED.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
