"""
Case API schemas.

These are the shapes used at the API boundary - what a client sends
when creating a case, and what the API sends back in response. They
are intentionally separate from app.models.case.Case, which is the
internal data model used throughout the rest of the application.

No database, ORM, or route logic lives here - just request/response
shapes with simple validation.
"""

from datetime import datetime

from pydantic import BaseModel, Field


class CaseCreate(BaseModel):
    """
    Fields a client must provide to create a new case.

    Notably absent: `id` and `created_at`. Those aren't something the
    client should be supplying - they get generated by the application
    when the case is actually created.
    """

    name: str = Field(..., min_length=1, description="Short human-readable case name.")
    description: str = Field(..., min_length=1, description="Longer description of what the case covers.")

    class Config:
        json_schema_extra = {
            "example": {
                "name": "Phone Seizure 04-2026",
                "description": "Suspect device analysis following warrant #2026-0042.",
            }
        }


class CaseResponse(BaseModel):
    """
    Shape of a case as returned by the API.

    Includes everything a client might want to see about a case,
    including fields the client never supplies directly (`id`,
    `created_at`), which are filled in by the application.
    """

    id: str
    name: str
    description: str
    created_at: datetime

    class Config:
        json_schema_extra = {
            "example": {
                "id": "3f9a1c2e-8b4d-4e6a-9c1a-7d2f5b6e9a10",
                "name": "Phone Seizure 04-2026",
                "description": "Suspect device analysis following warrant #2026-0042.",
                "created_at": "2026-09-18T10:15:30Z",
            }
        }
